title:             BinaryCaesar
email:             BinaryCaesar@gmail.com
description:       If you can't tell, does it matter?
author:            BinaryCaesar
baseurl:           "/BinaryCaesar.github.io"
url:               "http://BinaryCaesar.github.io"

# Social Profiles
github_username:   BinaryCaesar
wechat_public_account: 造物神物色的神怪

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
